# Generated by Django 6.1.1 on 2026-09-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='room',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
