# Generated by Django 6.1.1 on 2026-09-27 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='channels_sent',
            field=models.CharField(default='SMS, Email, Push Notification', max_length=255),
        ),
    ]
