# Generated by Django 6.1.1 on 2026-09-27 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_alert_channels_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='acknowledged_by',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('TACHYCARDIA', 'Tachycardia'), ('BRADYCARDIA', 'Bradycardia'), ('HYPOXIA', 'Hypoxia'), ('HIGH_TEMP', 'High Temperature'), ('FALL_DETECTED', 'Fall Detected'), ('SOS_EMERGENCY', 'SOS Emergency'), ('THRESHOLD_BREACH', 'Threshold Breach')], default='THRESHOLD_BREACH', max_length=30),
        ),
        migrations.AddField(
            model_name='alert',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='resolved_by',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='alert',
            name='source',
            field=models.CharField(default='hardware', max_length=20),
        ),
        migrations.AddField(
            model_name='alert',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('ACKNOWLEDGED', 'Acknowledged'), ('RESOLVED', 'Resolved')], default='NEW', max_length=15),
        ),
        migrations.AddField(
            model_name='alert',
            name='threshold',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='alert',
            name='value',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
