import {
  LayoutDashboard,
  Activity,
  Users,
  Bell,
  BellRing,
  FileText,
  FileSpreadsheet,
  Settings,
  Sliders,
  LogOut,
  User,
  AlertTriangle,
  AlertOctagon,
  CheckCircle2,
  XCircle,
  Clock,
  Cpu,
  Radio,
  HardDrive,
  HeartPulse,
  Droplets,
  Thermometer,
  ShieldCheck,
  Stethoscope,
  HeartHandshake,
  WifiOff,
  FlaskConical,
  Search,
  Eye,
  EyeOff,
  Lock,
  Mail,
  RefreshCw,
  Play,
  PhoneCall,
  ChevronRight,
  ChevronDown,
  Download,
  Check,
  X,
  Compass,
  ArrowUpRight,
  ArrowDownRight,
  SlidersHorizontal,
  Flame,
} from 'lucide-react';

export {
  LayoutDashboard as IconDashboard,
  Activity as IconActivity,
  Users as IconUsers,
  Bell as IconBell,
  BellRing as IconBellRing,
  FileText as IconFileText,
  FileSpreadsheet as IconFileSpreadsheet,
  Settings as IconSettings,
  Sliders as IconSliders,
  LogOut as IconLogOut,
  User as IconUser,
  AlertTriangle as IconAlertTriangle,
  AlertOctagon as IconAlertOctagon,
  CheckCircle2 as IconCheckCircle,
  XCircle as IconXCircle,
  Clock as IconClock,
  Cpu as IconCpu,
  Radio as IconRadio,
  HardDrive as IconHardDrive,
  HeartPulse as IconHeartPulse,
  Droplets as IconDroplets,
  Thermometer as IconThermometer,
  ShieldCheck as IconShieldCheck,
  Stethoscope as IconStethoscope,
  HeartHandshake as IconHeartHandshake,
  WifiOff as IconWifiOff,
  FlaskConical as IconFlask,
  Search as IconSearch,
  Eye as IconEye,
  EyeOff as IconEyeOff,
  Lock as IconLock,
  Mail as IconMail,
  RefreshCw as IconRefresh,
  Play as IconPlay,
  PhoneCall as IconPhoneCall,
  ChevronRight as IconChevronRight,
  ChevronDown as IconChevronDown,
  Download as IconDownload,
  Check as IconCheck,
  X as IconX,
  Compass as IconCompass,
  ArrowUpRight as IconArrowUpRight,
  ArrowDownRight as IconArrowDownRight,
  SlidersHorizontal as IconSlidersHorizontal,
  Flame as IconFlame,
};

const ClinicalIcons = {
  IconDashboard: LayoutDashboard,
  IconActivity: Activity,
  IconUsers: Users,
  IconBell: Bell,
  IconHeartPulse: HeartPulse,
  IconDroplets: Droplets,
  IconThermometer: Thermometer,
  IconShieldCheck: ShieldCheck,
  IconWifiOff: WifiOff,
  IconFlask: FlaskConical,
};

export default ClinicalIcons;
