# Generated by Django 6.1.1 on 2026-09-26 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VitalReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_timestamp', models.BigIntegerField()),
                ('heart_rate', models.FloatField()),
                ('spo2', models.FloatField()),
                ('temperature', models.FloatField()),
                ('motion_flag', models.BooleanField(default=False)),
                ('sos_pressed', models.BooleanField(default=False)),
                ('state', models.CharField(max_length=10)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='patients.patient')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
    ]
