# Generated by Django 6.1.1 on 2026-09-27 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitalreading',
            name='source',
            field=models.CharField(choices=[('hardware', 'Hardware'), ('simulation', 'Simulation')], default='hardware', max_length=20),
        ),
    ]
